# deploy to travis - beta

language: node_js
node_js:
  - '10'
install:
    - npm install
script:
    - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: xiao8346/xiao8346.github.io
  target_branch: master